# Generated by Django 3.1.5 on 2021-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100000)),
                ('web_url', models.CharField(max_length=100000)),
                ('Name', models.CharField(max_length=10000)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
