# Generated by Django 3.1.5 on 2021-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0004_frame_image_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='image_width',
            field=models.CharField(default=0, max_length=10000),
        ),
    ]
