# Generated by Django 3.1.5 on 2021-04-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0005_frame_image_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='order',
        ),
    ]
