# Generated by Django 3.1.5 on 2021-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0006_remove_collection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
