# Generated by Django 3.1.5 on 2021-04-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0007_auto_20210415_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frame',
            new_name='Binging',
        ),
    ]
