# Generated by Django 3.1.5 on 2021-05-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0010_content_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content_names',
        ),
    ]
