# Generated by Django 3.1.5 on 2021-05-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0011_delete_content_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image_width',
        ),
    ]
