# Generated by Django 3.1.5 on 2021-05-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0012_remove_collection_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_height',
            field=models.FloatField(default=0),
        ),
    ]
