# Generated by Django 3.1.5 on 2021-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0013_auto_20210503_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='save_number',
            field=models.IntegerField(default=0),
        ),
    ]
