# Generated by Django 3.1.5 on 2021-05-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0014_collection_save_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user_id', models.IntegerField(default=0)),
                ('other_id', models.IntegerField(default=0)),
            ],
        ),
    ]
