# Generated by Django 3.1.5 on 2021-05-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0015_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='save_number',
            new_name='save_count',
        ),
    ]
