# Generated by Django 3.1.5 on 2022-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffler', '0017_auto_20210511_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='domain',
            field=models.IntegerField(default=1),
        ),
    ]
